// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/task/claim": {
            "post": {
                "description": "Current user request to claim a task",
                "tags": [
                    "Task"
                ],
                "summary": "Current user request to claim a task",
                "responses": {}
            }
        },
        "/task/status": {
            "get": {
                "description": "Get current user all tasks status and related info",
                "tags": [
                    "Task"
                ],
                "summary": "Get current user all tasks status and related info",
                "responses": {}
            }
        },
        "/user/claim": {
            "post": {
                "description": "Current user request claim daily checkin",
                "tags": [
                    "User"
                ],
                "summary": "Current user request claim daily checkin",
                "responses": {}
            }
        },
        "/user/invited": {
            "get": {
                "description": "Get current user's invited user list",
                "tags": [
                    "User"
                ],
                "summary": "Get current user's invited user list",
                "responses": {}
            }
        },
        "/user/login": {
            "post": {
                "description": "User login in by Telegram mini app initData",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User request to log in, return user info and session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.UserLoginRes"
                        }
                    }
                }
            }
        },
        "/user/point": {
            "get": {
                "description": "Get current user's point",
                "tags": [
                    "User"
                ],
                "summary": "Get current user's point",
                "responses": {}
            }
        }
    },
    "definitions": {
        "api.UserLoginRes": {
            "type": "object",
            "properties": {
                "checkin": {
                    "$ref": "#/definitions/dbs.Checkin"
                },
                "isNew": {
                    "type": "boolean"
                },
                "session": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dbs.User"
                }
            }
        },
        "dbs.Checkin": {
            "type": "object",
            "properties": {
                "continuousDays": {
                    "description": "continuous day counter",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "created ts: 1670400478555",
                    "type": "integer"
                },
                "id": {
                    "description": "unique id, generated by uuid4",
                    "type": "string"
                },
                "rewardPoint": {
                    "description": "rewardPoint for this continuous checkin",
                    "type": "integer"
                },
                "status": {
                    "description": "checkin status: 0: unclaimed, 1: claimed",
                    "type": "integer"
                },
                "uid": {
                    "description": "checkin user id",
                    "type": "integer"
                }
            }
        },
        "dbs.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "created ts: 1670400478555",
                    "type": "integer"
                },
                "id": {
                    "description": "user id, generate by Telegram, which means Telegram user id",
                    "type": "integer"
                },
                "isPremium": {
                    "description": "is premium user",
                    "type": "boolean"
                },
                "languageCode": {
                    "description": "user language code",
                    "type": "string"
                },
                "referralCode": {
                    "description": "current user's referral code, generate when user first login",
                    "type": "string"
                },
                "referralUid": {
                    "description": "current user referral user id, which who has referral current user",
                    "type": "integer"
                },
                "username": {
                    "description": "username in Telegram",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
